
@urlcalendario = http://127.0.0.1:3000/api/calendario
###

GET {{urlcalendario}} HTTP/1.1

###

GET {{urlcalendario}}/julio HTTP/1.1

###
GET {{urlcalendario}}/agosto HTTP/1.1

###
POST {{urlcalendario}}/agosto HTTP/1.1
Content-Type: application/json

{
    "dia": 16,
    "horario": "12:00",
    "actividad": "cumple Mamá y papá"
}

###

PATCH {{urlcalendario}}/julio/6
Content-Type: application/json

{
  "horario": "12:00",
  "actividad": "vacaciones con la familia"
}

###

PATCH {{urlcalendario}}/agosto/1
Content-Type: application/json

{
  "horario": "12:00",
  "actividad": "asadito con amigos"

}

###
DELETE {{urlcalendario}}/julio/1 HTTP/1.1


###
DELETE {{urlcalendario}}/agosto/12 HTTP/1.1

